version = "2"

[linters]
default = "none"
enable = [
  "unparam",
  "govet",
  "unused",
  "ineffassign",
  "staticcheck",
  # "errcheck",
  "funcorder",
  "whitespace",
]

[formatters]
enable = ["gofmt", "goimports"]
