coverage:
  paths:
    - coverage.out
  exclude:
  - "**/*_gen.go"
  - "**/mock/*.go"
codeToTestRatio:
  code:
    - "**/*.go"
    - "!**/*_test.go"
    - "!**/*_gen.go"
    - "!**/mock/*.go"
  test:
    - "**/*_test.go"
testExecutionTime:
  if: true
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
