coverage:
  status:
    project:
      default:
        threshold: 10%
status:
  patch:
    default:
      threshold: 10%
comment:
  layout: "reach, diff, flags, files, Header, Footer"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  hide_project_coverage: false
