coverage:
  status:
    patch:
      default:
        target: 30%
        threshold: 10%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    project:
      default:
        target: 30%
        threshold: 10%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files, Header, Footer"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  hide_project_coverage: false
