coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "reach, diff, flags, files, Header, Footer"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  hide_project_coverage: false
