name: go-test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.go"
  workflow_dispatch:
permissions: write-all

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Check lint
        run: make lint
        shell: bash
      - name: Check vulnerability
        run: make vulncheck
        shell: bash
      # ビルド
      - name: Build
        run: make build
        shell: bash
      # テスト実行
      - name: Run Tests
        run: make ci-test
      - name: create report
        uses: k1LoW/octocov-action@v1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
